[package]
name = "toad"
version = "0.4.1"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.57", features = ["derive"] }
colored = "3.1.1"
discovery = { version = "0.4.1", path = "../../crates/discovery" }
indicatif = "0.17"
rayon = "1.10"
scaffold = { path = "../../crates/scaffold" }
toad-core = { version = "0.4.1", path = "../../crates/toad-core" }
toad-git = { path = "../../crates/toad-git" }
toad-manifest = { version = "0.4.1", path = "../../crates/toad-manifest" }
toad-ops = { path = "../../crates/toad-ops" }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3.10"
