[package]
name = "toad"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.57", features = ["derive"] }
colored = "3.1.1"
discovery = { version = "0.1.0", path = "../../crates/discovery" }
scaffold = { path = "../../crates/scaffold" }
