[workspace]
members = [
  "bin/toad",
  "crates/*",
  "crates/toad-git",
  "crates/toad-ops",
]
resolver = "2"

[workspace.package]
authors = ["Primatif"]
homepage = "https://github.com/Primatif/Primatif_Toad"
repository = "https://github.com/Primatif/Primatif_Toad"
