[workspace]
members = [
  "bin/toad",
  "crates/*",
  "crates/toad-git",
  "crates/toad-ops",
]
resolver = "2"

[workspace.package]
license = "MIT"
homepage = "https://github.com/MaterDev/Primatif_Toad"
repository = "https://github.com/MaterDev/Primatif_Toad"
authors = ["Primatif"]
