[package]
name = "toad-core"
version = "1.0.1"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0.100"
dirs = "6.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
toml = "0.8.23"

[dev-dependencies]
filetime = "0.2"
tempfile = "3.10"
